### ISSUE TITLE
Create Carousel Component

### ISSUE THREAD

**Issue by dnkemper** [uiowa/uids#123]
## Problem

The Carousel/Carousel Item paragraph bundles are built with Bootstrap components and only covered by uiowa_bootstrap.

[i1304](https://github.com/uiowa/uiowa/issues/1304)- When comparing SiteNow to UIDS, UIDS is missing a carousel component 

## Proposed Solution

Create prototype UIDS component(s) for Carousel/Carousel Item (image) using [Slick](https://kenwheeler.github.io/slick/)?

Maintain paragraph bundle options (crossfade, captions, caption bg color) and leave it flexible so that non-image carousel items can be introduced in the future similar to how it currently is setup (e.g. cards).

Follow up in uids_base (uiowa/uiowa/issues/1660) to cover the existing paragraph bundle functionality.

**Comment by joewhitsitt** [comment]
Is Slick okay with everyone?

**Comment by bspeare** [comment]
That works for me!

**Comment by GaryRidgway** [comment]
Initial attempt for this done here https://github.com/uiowa/uids/tree/uids-carousel and PR here https://github.com/uiowa/uids/pull/246

**Comment by bspeare** [comment]
This work is complete and was done in https://github.com/uiowa/uiowa/pull/1776.
