### ISSUE TITLE
Views field content text not matching standard site text

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uids#138]
Text within views fields are not matching the standard text for the site. Nested tags to show depth:

div class="view-content"
 -- div class="views-row"
 ---- span class="views-field views-field-fieldnamehere" (may or may not exist for field)
 ------ span class="field-content"

This should be default views field naming unless it's been changed inside the view.

**Comment by bspeare** [comment]
https://policy.clas.uiowa.edu/a-z

**Comment by bspeare** [comment]
I don't think this is still an issue so I am going to close this for now.
