### ISSUE TITLE
Adjust page title font weight

### ISSUE THREAD

**Issue by bspeare** [uiowa/uids#143]
# Problem 

It is currently set to 700. 

# Proposed Solution

Set weight to 600 in https://github.com/uiowa/uids/blob/master/components/01%20-%20elements/headings/_headings.scss

**Comment by mark-bennett-uiowa** [comment]
I like it at 700 actually. But thats just my opinion. Id rather have smaller h2-h6. I think the h1 is perfect! :)

**Comment by bspeare** [comment]
I like it too! :)
