### ISSUE TITLE
Support versioned docs in gh-pages branch with latest or preview capability

### ISSUE THREAD

**Issue by pyrello** [uiowa/uids#156]
# Problem
Currently, there is no way to review changes that affect the rendered output of https://uiowa.github.io/uids without merging a PR into the master branch. At that point, it become published and authoritative. It would be nice to introduce a way for non-developers to review PR changes.

# Proposed solution
Refactor the current build process so that when a PR is merged into `master`, the new build is moved into a directory inside the `gh-pages` branch called `latest`. Also, create a `develop` branch, and when that branch is pushed to, it also triggers a deployment which gets placed in a folder called `dev` in the `gh-pages` branch.

**Comment by richardbporter** [comment]
I'm not sure this will work as outlined. Each branch, develop and master, would have to generate both folders otherwise the other will not exist. For example, a push to develop would build into dev but without also building into latest, the latter directory would be empty since the entire gh-pages branch is force-pushed to GitHub Pages.

I wonder how other systems solved this.

**Comment by pyrello** [comment]
I think they use something other than Github pages :)

**Comment by pyrello** [comment]
@richardbporter I was wrong, I guess: https://github.com/twbs/bootstrap/tree/gh-pages/docs. Bootstrap uses Github pages (and has for a while, I think). They have a process for versioning their docs inside the `gh-pages` branch. I haven't quite worked out the whole sequence, but it either involves this line:
https://github.com/twbs/bootstrap/blob/5faf41eb4837491fa8193910c5816efadb4dbc5a/package.json#L60
or this one:
https://github.com/twbs/bootstrap/blob/5faf41eb4837491fa8193910c5816efadb4dbc5a/package.json#L67
and also possibly this script file:
https://github.com/twbs/bootstrap/blob/master/build/ship.sh

**Comment by pyrello** [comment]
I have been investigating this some more and I think that a good potential path forward is to use Github Actions (https://github.com/uiowa/uids/actions/new). It seems a bit more flexible than Travis for our purposes in that you can define multiple workflows with multiple steps per workflow and environmental variables that get passed around. Additionally, the steps can be defined as another action that has already been created. There are predefined actions for creating a release, uploading release assets, and much more.
