### ISSUE TITLE
Decrease logo tab overlap to create more space for main navigation

### ISSUE THREAD

**Issue by bspeare** [uiowa/uids#162]
# Problem

<img width="1794" alt="Screen Shot 2020-04-30 at 1 49 10 PM" src="https://user-images.githubusercontent.com/1036433/80748205-2bcc2180-8aea-11ea-9429-7b2605c242f8.png">

# Proposed Solution

<img width="1737" alt="Screen Shot 2020-04-30 at 1 49 03 PM" src="https://user-images.githubusercontent.com/1036433/80748218-325a9900-8aea-11ea-9279-c8ed56f300e4.png">

**Comment by mark-bennett-uiowa** [comment]
I like the less overlap, but it looks to me like the size of the IOWA decreased also. Can we keep that the same size and just decrease the padding/margin to create less overlap?

**Comment by bspeare** [comment]
@mark-bennett-uiowa Definitely, the screenshot is meant more to illustrate the tab overlap - ignore the rest! :)

**Comment by mark-bennett-uiowa** [comment]
@bspeare sweet, thanks bud!
