### ISSUE TITLE
Fix page title wrap when used in the hero component

### ISSUE THREAD

**Issue by bspeare** [uiowa/uids#172]
# Problem

<img width="1506" alt="Screen Shot 2020-05-07 at 1 12 10 PM" src="https://user-images.githubusercontent.com/1036433/81331639-807e1800-9067-11ea-8701-08f5ae906be3.png">

# Proposed Solution

Adjust container width on hero grid.

**Comment by joewhitsitt** [comment]
is there font resize for mobile?

**Comment by bspeare** [comment]
Here's the mobile view

![Uploading Screen Shot 2020-05-07 at 1.40.58 PM.png…]()

**Comment by joewhitsitt** [comment]
ah but it doesn't try to fit in the image. good!
