### ISSUE TITLE
As a developer, I can visit uids.brand.uiowa.edu on May 26 and view a simplified list of components labeled as 'ready'

### ISSUE THREAD

**Issue by bspeare** [uiowa/uids#178]
Before uiowa.edu and brand.uiowa.edu launch, these updates need to be made to UIDS. 

# Overview Page

- [ ] Write up instructions for //uids.brand.uiowa.edu

# Visible Components

Labeled as `Ready` https://fractal.build/guide/core-concepts/statuses.html#setting-the-status-of-an-item

- [ ] Alerts
- [ ] Card component
- [ ] Accordion
- [ ] Simple brand bar variant https://github.com/uiowa/uids/issues/92#issuecomment-608101642
- [ ] Footer
- [ ] Buttons?
- [ ] Hide the rest?

# Permissions

- [ ] How can anyone contribute?

**Comment by joewhitsitt** [comment]
Wishlist Item: uids.brand.uiowa.edu domain CNAME instead of github.io?

**Comment by bspeare** [comment]
@joewhitsitt I think that CNAME would be great!

**Comment by joewhitsitt** [comment]
working on the CNAME

**Comment by richardbporter** [comment]
Is this done? Its a bit past May 26... :)

**Comment by bspeare** [comment]
Closing this since we are long past the launch date of May 26.
