### ISSUE TITLE
Support uids buttons in uids footer

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uids#200]
## Problem
uids footer styles target all `<a>` tags which causes issues for uids buttons.

<img width="629" alt="Screen Shot 2020-05-20 at 4 33 19 PM" src="https://user-images.githubusercontent.com/4663676/82499678-bb486d00-9ab7-11ea-8673-61650e0aaf79.png">

**Comment by bspeare** [comment]
Now that the footer has been restricted to minimal HTML, I think we can close this issue because of https://github.com/uiowa/uiowa/pull/4269.   The footer guidelines have also be updated to explain what is allowed in the footer https://brand.uiowa.edu/applying-brand/web.
