### ISSUE TITLE
Home Page - Create Background Video/Image Component

### ISSUE THREAD

**Issue by bspeare** [uiowa/uids#23]
**Create a background image/video component that contains:**

- Background video loop 
- Vertically centered headline with links below
- Vertical gradient opacity overlay for accessibility
- Pause/play button in lower left hand corner?

Example from mockup:

<img width="674" alt="Screen Shot 2020-01-30 at 8 06 40 PM" src="https://user-images.githubusercontent.com/1036433/73506864-99a66700-439c-11ea-8b4d-826f04fe1d39.png">

**Possible variant with background/inline image:**

- Left/bottom aligned headline within page container
- Background image/inline image

Example from mockup:

<img width="996" alt="Screen Shot 2020-01-30 at 8 07 14 PM" src="https://user-images.githubusercontent.com/1036433/73506931-cf4b5000-439c-11ea-8070-fc08c40e3ec4.png">

**Additional thoughts:**

- Vertical centering and left/bottom alignment should probably be added through container/wrapper classes that use a yet to be created mixin/extend from _utilities.scss

**Comment by joewhitsitt** [comment]
Let me know if I should make any of the tweaks. Otherwise, removing my assignment for now.
