### ISSUE TITLE
No black background option for sections

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uids#234]
For a CTA block within a section, I have the option for:

- Block Background Style: Black
- Block Background Style: Brain Pattern Black
- Block Background Style: Gold
- Block Background Style: Gray

However, for the containing section, I can only select:

- Section Background Style: Brain Pattern
- Section Background Style: Brain Pattern Black
- Section Background Style: Brain Pattern Reversed
- Section Background Style: Gold
- Section Background Style: Gray

There isn't an option for a plain black background (without a pattern) for sections.

**Comment by bspeare** [comment]
This work was completed in https://github.com/uiowa/uiowa/pull/1770.
