### ISSUE TITLE
Centered hero block description text is off-centered

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uids#245]
### Problem

When using the default centered text in a hero block, the description text is off-centered if viewed at standard widths or higher:
<img width="1680" alt="Screen Shot 2020-06-15 at 9 40 16 AM" src="https://user-images.githubusercontent.com/3067017/84671257-c3e06780-aeec-11ea-9b4e-248cd33562f7.png">

The section is setup as a one-column section, using Section Margin: Edge-to-Edge and Section Margin: Remove Default Margins. The block is setup as a Hero block with a simple H1 heading using left- or center-aligned text in the description field, with no overrides.

At widths around 700-800px, it appears correct in preview and live modes, but higher widths the description starts to drift left.

### Solution

The only way I was able to adjust any styling to fix this was to remove the following completely, though a better solution is probably more helpful. There was no other styling on that region that was causing the drift that I could see:

<img width="1680" alt="Screen Shot 2020-06-15 at 9 40 34 AM" src="https://user-images.githubusercontent.com/3067017/84672571-4fa6c380-aeee-11ea-82f6-97c4c5ea9f3f.png">

```
@media (min-width: 768px)
.hero.hero__center p {
    margin: 0 20%;
}
```

**Comment by bspeare** [comment]
@mark-bennett-uiowa Is this on dev, stage, or prod url that I can preview?

**Comment by mark-bennett-uiowa** [comment]
@bspeare I knew the minute I submitted that, that you would ask. Here ya go: [https://nativeamericanstudies.prod.drupal.uiowa.edu/](https://nativeamericanstudies.prod.drupal.uiowa.edu/). Thanks bud!
