### ISSUE TITLE
Alert styles (wysiwyg) need some padding

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uids#280]
## Problem

Lacking left/right padding for wrapping text.

<img width="675" alt="Screen Shot 2020-07-09 at 4 30 24 PM" src="https://user-images.githubusercontent.com/4663676/87175251-03a52f80-c29e-11ea-83fb-9d0ad63a2b35.png">

When this change has been made, remove the override in the alert.scss file in UIDS Base.

**Comment by pyrello** [comment]
I moved this to UIDS because it needs to be resolved here eventually.

**Comment by bspeare** [comment]
Here's a another use of alerts in the wild: https://diversity.uiowa.edu/action-planning/diversity-equity-and-inclusion-action-plan-updates

<img width="1400" alt="Screen Shot 2020-07-17 at 4 21 38 PM" src="https://user-images.githubusercontent.com/1036433/87831647-b3077680-c849-11ea-9090-23755566fb51.png">
