### ISSUE TITLE
Section backgrounds have side gaps at smaller widths

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uids#288]
Create a new section with a solid background color and set to Margin: Edge-to-edge. Decrease the width of the browser viewport to less than 1335 pixels wide and a new gap on the sides of the section appears. This gap does not carry over the background color.
<img width="321" alt="Screen Shot 2020-07-22 at 1 52 32 PM" src="https://user-images.githubusercontent.com/3067017/88216833-47dfea80-cc23-11ea-8ae1-9d68ca9e344d.png">
<img width="202" alt="Screen Shot 2020-07-22 at 1 54 08 PM" src="https://user-images.githubusercontent.com/3067017/88216842-4a424480-cc23-11ea-9490-ccdcbb2c9b48.png">
See [https://globalhealthstudies.prod.drupal.uiowa.edu/undergraduate](https://globalhealthstudies.prod.drupal.uiowa.edu/undergraduate) for an example of this.

**Comment by bspeare** [comment]
It looks like these have a style of "fixed width container" which is causing the spacing.  I went into one of the sections and removed that style and the spacing went away.

**Comment by mark-bennett-uiowa** [comment]
That did it. Thanks bud. Closing issue.
