### ISSUE TITLE
As an Admissions stakeholder, I can view a microsite of the admissions viewbook

### ISSUE THREAD

**Issue by bspeare** [uiowa/uids#290]
# Next Steps

**In UIDS** (https://github.com/uiowa/uids/pull/292)
- [x] Build out vertical menu component for navigation.
- [x] Add hover transition for small Hero component.
- [x] Add similar link strategy to Hero component that Card component is using.
- [x] Add Amnesty font to project. 
- [x] Move single word highlight headline treatment back into headline component. 
- [x] Move numbered list style adjustments used in Apply section back into lists component. 
- [x] User Hero variant for academic areas instead of creating new card variant.
- [x] Move horizontal stat variant created for viewbook back into stat component as a variant.

**In Admissions Viewbook** (https://github.com/uiowa/admissions-viewbook)
- [x] Create build process and GitHub pages site
- [x] Point domain name to GitHub Pages url
- [x] Create Readme for watch/build process
- [x] Push up a PR with card component work from @GaryRidgway 
- [x] Update card component so that it directly consumes styles and js from UIDS
- [x] Determine what needs to be done for js to be imported and used within component
- [x] Campus-wide GTM snippet
- [x] Admissions tracking snippet

**Comment by bspeare** [comment]
Other viewbook sites:

- https://www.augusta.edu/admissions/viewbook/
- https://view.emich.edu/
- http://experience.admission.ucla.edu/ 

Design ideas:

- Scroll snap sections? https://css-tricks.com/practical-css-scroll-snapping/
- ?

**Comment by mjoneill** [comment]
We need to add two Google Tag Manager containers to get the appropriate GA on the site:
Campus-wide & a site-specific container (this will contain the site-specific GA).  Both GTM Container code snippets are attached. 

[tag-manager-campus-wide.txt](https://github.com/uiowa/uids/files/5041680/tag-manager-campus-wide.txt)


[admissions-viewbook-tag-manager.txt](https://github.com/uiowa/uids/files/5041668/admissions-viewbook-tag-manager.txt)

@bspeare
