### ISSUE TITLE
Make table component responsive

### ISSUE THREAD

**Issue by bspeare** [uiowa/uids#302]
# Problem

The current table solution is not responsive. 

<img width="475" alt="Screen Shot 2020-08-25 at 9 53 05 AM" src="https://user-images.githubusercontent.com/1036433/91191433-66218600-e6ba-11ea-9421-52bdff8032b1.png">

# Proposed Solution

Which responsive table method is preferred?

- This solution seems like a good method: https://codepen.io/team/css-tricks/pen/wXgJww
- Any other suggestions?

**Comment by bspeare** [comment]
Next steps:

- Set up a horizontal scroll option with sticky headers
- Set up a secondary solution with responsive columns

**Comment by GaryRidgway** [comment]
this at a base level is covered by #306

**Comment by bspeare** [comment]
Closed via https://github.com/uiowa/uids/pull/306
