### ISSUE TITLE
Account for background options behind menu block navs

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uids#305]
## Problem

The internal page menu blocks don't work with all background colors

**Comment by bspeare** [comment]
# Proposed Solution

Remove link color from https://github.com/uiowa/uids/blob/main/src/components/menus/main-menu/main-menu.scss#L21
Set a rule for `:not([class*=bg-])` to set `color: $secondary`

**Comment by joewhitsitt** [comment]
This was covered by https://github.com/uiowa/uids/issues/480
