### ISSUE TITLE
Combine event styles into card

### ISSUE THREAD

**Issue by pyrello** [uiowa/uids#309]

**Comment by bspeare** [comment]
- Change date to Roboto
- Create variants in UIDS for lists and image sizes/masks

**Comment by bspeare** [comment]
Date change request from brand team listed below in the screenshot:

<img width="592" alt="Screen Shot 2020-10-02 at 10 33 14 AM" src="https://user-images.githubusercontent.com/1036433/94941805-0d07f780-049b-11eb-9b52-78a202785533.png">

**Comment by GaryRidgway** [comment]
Okay, after doing some more work on https://github.com/uiowa/uiowa/pull/2255, I think the following has to be done for events to be"complete AFTER we merge https://github.com/uiowa/uiowa/pull/2255.

- [ ] refactor classes in both the events teaser template and the events.scss file to better match what they are. They are not necessarily “Cards” so they should probably be changed.
- [ ] work on both uids and uids base at the same time to refactor any relevant styles for teasers back in to uids from uids base.
- [ ] change the date field in uids to be roboto

**Comment by pyrello** [comment]
Based on conversations today with @bspeare and @GaryRidgway, I think that the best way to move forward it to combine the current event component into the card, since they are essentially the same thing for all intents and purposes. Here are the steps forward to make that happen in UIDS:
* Add css classes to the card.scss file within the `card__` or `card--` BEM namespace that allow for options that are currently represented in the event component:
  - Circular image treatment
  - Date styling (could possibly just use sub-heading/author style)
  - Location icon
  - Image alignment (left or right) when using a horizontal variation.
* Additionally add option to set different image sizes when using a horizontal variation in a card.
* Create a variant for the card to demonstrate using it for an event.
* After uiowa/uiowa#2306 is completed, remove the event component entirely.

I think we should reconsider the pointing on this based on these changes.
