### ISSUE TITLE
Remove top padding for first-child items using element--flex-left class

### ISSUE THREAD

**Issue by bspeare** [uiowa/uids#318]
# Problem 

Stats have extra top padding when the `element--flex-left` class is used. 

<img width="1517" alt="Screen Shot 2020-09-23 at 3 29 38 PM" src="https://user-images.githubusercontent.com/1036433/94066182-bbcc7980-fdb1-11ea-829b-b5265b1f2799.png">

**Comment by pyrello** [comment]
This is going to be closed by a commit to uiowa/uiowa because it is more appropriately solved there.
