### ISSUE TITLE
Slider - Fade-in content after slide is done moving

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uids#320]
## Problem

As a slide is being revealed, it is a bit jarring to see the text responsively adjust to the growing container.

## Suggestion

Create a transition to fade-in the content after the slider transition is done.

**Comment by joewhitsitt** [comment]
Awesome and thanks @bspeare

**Comment by bspeare** [comment]
Is this transition better or too slow?  https://uids.brand.uiowa.edu/branches/feature_lb_feature_maturity/components/detail/slider--default.html

**Comment by joewhitsitt** [comment]
seeing as the length could be long or short, it is okay as-is.
