### ISSUE TITLE
Update stat-block component to use new styles

### ISSUE THREAD

**Issue by bspeare** [uiowa/uids#35]
Update stat-block to use new styles: https://github.com/uiowa/uids/tree/master/components/02%20-%20blocks/stat-block

- Change font to Antonio Bold
- Add left aligned and vertically centered variants
- How to handle percentages? We don't want them to be same font size as main stat. 

<img width="235" alt="Screen Shot 2020-02-05 at 9 48 24 AM" src="https://user-images.githubusercontent.com/1036433/73857847-1dc57800-47fd-11ea-8dd4-686c88b706eb.png">
<img width="338" alt="Screen Shot 2020-02-05 at 9 48 08 AM" src="https://user-images.githubusercontent.com/1036433/73857848-1dc57800-47fd-11ea-89be-9dbb0de36895.png">

**Comment by joewhitsitt** [comment]
I think the prefix/suffix stuff can easily be handled if we update heading to include those options variables as spans within the heading tag, then style the spans specific to the stat. Thoughts on touching heading as part of this @bspeare?

**Comment by bspeare** [comment]
I think that could be a good direction - do you want to give it a shot?

**Comment by joewhitsitt** [comment]
sure

**Comment by bspeare** [comment]
![brain-pattern](https://user-images.githubusercontent.com/1036433/73866603-c0d0be80-480a-11ea-8a3d-ae2ea5a8e06e.png)
