### ISSUE TITLE
Style accordion headings below h2

### ISSUE THREAD

**Issue by cory-skeers** [uiowa/uids#385]
Currently accordion heading styles target h2, though DOM structure might place them at a lower level.

![image](https://user-images.githubusercontent.com/49074566/96740320-5a82d080-1386-11eb-8f3e-8ba4afd78c04.png)

# Proposed solution
Update scss to target h3-h6 as well as h2.

**Comment by joewhitsitt** [comment]
`.accordion__heading` should be able to be used instead to cover all headings

**Comment by cory-skeers** [comment]
Ah...thanks @joewhitsitt! Updated it to use the class in the PR.

**Comment by cory-skeers** [comment]
Closed by #386
