### ISSUE TITLE
Update banner component to allow for a background video

### ISSUE THREAD

**Issue by bspeare** [uiowa/uids#394]
- [x] move over hero.js and refactor 
- [x] Add pause/play button styles to banner. 
- [x] Update template refactor
- [x] More scss updates

[A PR to track progress for this has been started here](https://github.com/uiowa/uids/pull/412)

**Comment by joewhitsitt** [comment]
Will need to account for what the expected behavior is when different banner heights are selected. I remember this being a concern with the video team when we first built the hero display. (e.g. cropping/scaling/center focus, etc.)

**Comment by bspeare** [comment]
Closed via https://github.com/uiowa/uids/pull/412.
