### ISSUE TITLE
Open accordion item based on URL anchor

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uids#396]
## Issue

Accordions have a unique id that can be targeted (e.g. https://sitenow.uiowa.edu/faqs#heading351), but doesn't currently open the item.

## Proposed Solution

Make it happen!

**Comment by bspeare** [comment]
Related issue: https://github.com/uiowa/uids/issues/112

**Comment by GaryRidgway** [comment]
This should probably include some of the enhancements that we made for the hashTabs such as:

- [ ] displaying all data when no JS or css is present
- [ ] changing the open accordion based on a change in the URL
- [ ] Being able to set any ID you want and have it still work
