### ISSUE TITLE
Naming convention for twig blocks?

### ISSUE THREAD

**Issue by pyrello** [uiowa/uids#40]
Consider the following example:
```twig
{% extends '@header' %}

{% block action_menu %}
    stuff
{% endblock %}
```

Should the block be named 'action_menu'? Or 'action-menu'? I tried to look up what the best practice or convention around this was, but trying to search for something related to Drupal with the word 'block' in it is pretty much a non-starter.

I guess I would lean towards the underscore (machine_name) approach because it allows you to select the name for copy/paste by double clicking rather than having to click and drag.

**Comment by bspeare** [comment]
From what I have seen in other themes, the underscore approach looks like the best practice.

**Comment by pyrello** [comment]
Sounds good. That's what I'll do.
