### ISSUE TITLE
Alternate colors for black button on gold background

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uids#411]
# Problem
This stems from #275 also. If you look at this image, you will see that the UIDS black button (bttn-secondary), it has a black background with white text, and a gold arrow.
![Screen Shot 2021-06-22 at 10 20 40 AM](https://user-images.githubusercontent.com/3067017/122952533-ac2f9080-d343-11eb-86f0-4fadb1264e07.png)

However, on the Give to Iowa CTA blocks on the CLAS pages appear as this (black background, gold text, white arrow):
<img width="1394" alt="Screen Shot 2020-11-12 at 4 30 55 PM" src="https://user-images.githubusercontent.com/3067017/99004307-76e8d780-2504-11eb-9cc2-28dbe49366ee.png">

Could we alternate these colors for CTA buttons, making the text white and arrow gold?

# Steps to reproduce
Create a new section with a gold background.
Create a new CTA block in the above section with a transparent background and give it some text and a link.

**Comment by bspeare** [comment]
@mark-bennett-uiowa do you have a page example where this is an issue?

**Comment by mark-bennett-uiowa** [comment]
@bspeare It's on any site if we have a gold background on a CTA block. I added an example to this page: [https://classtrategicplan.prod.drupal.uiowa.edu/](https://classtrategicplan.prod.drupal.uiowa.edu/) so you could see it. The way to get it to show up is with the Steps above. If you make the background of the CTA block gold as well, then the button changes to a white background with black text and a gold arrow. I included both examples so you can see the differences.

![Screen Shot 2021-06-23 at 11 53 25 AM](https://user-images.githubusercontent.com/3067017/123137494-a310f300-d419-11eb-98b2-71467b13a822.png)

**Comment by bspeare** [comment]
Thanks @mark-bennett-uiowa .   I think we need to get to https://github.com/uiowa/uids/issues/582 in order to resolve this issue.
