### ISSUE TITLE
Abstract "panel" component out of single open accordion

### ISSUE THREAD

**Issue by bspeare** [uiowa/uids#426]
# Problem

With the admissions site redesign, there is a need for a panel component for grouping areas of information on the page. 

<img width="464" alt="Screen Shot 2020-12-04 at 10 45 23 AM" src="https://user-images.githubusercontent.com/1036433/101210454-1ea48180-363b-11eb-94b6-6015bd0c9827.png">

<img width="429" alt="Screen Shot 2020-12-08 at 10 48 50 AM" src="https://user-images.githubusercontent.com/1036433/101514570-09816880-3943-11eb-9426-8bc82367e6ac.png">

# Proposed Solution

Add a variant of the accordion for a singular panel component that uses the accordion styles without the toggle option/icon.   This could also be a good place to start/address https://github.com/uiowa/uiowa/issues/1482. 

<img width="489" alt="Screen Shot 2020-12-04 at 10 50 52 AM" src="https://user-images.githubusercontent.com/1036433/101210606-62978680-363b-11eb-9e8b-a91e681c5da6.png">

**Comment by joewhitsitt** [comment]
might be confused on the terms here, but to me it sounds like panel would be a variant of accordion in uids, but a separate multi-value option in collection (aka accordion expanded, no js, no indicator)?

**Comment by bspeare** [comment]
@joewhitsitt That's a good question.   Do you think that would be a good place for it?

**Comment by joewhitsitt** [comment]
it makes sense to me until i start thinking about it more... the picture above says to me a single accordion item and collection could make sure the headings are set correctly and that additional panels could be placed together. i say all of this to avoid making card anymore complicated...

with that said, the next request will be to have separate "accordion options" per panel to make each one pop with a different color, etc. with that in mind, card sounds more appropriate but i shudder at the thought of dealing with that while keeping it simple for the editor.

i'd like to avoid a separate block type for this when both card and collection are so close at capturing this content.

Sorry for the bootstrap references but in v4 they moved "panel" to card and card makes up an accordion. https://getbootstrap.com/docs/4.5/migration/#panels

**Comment by pyrello** [comment]
My thoughts: 
* I disagree with the choice made in Bootstrap to use the card to build an accordion since it completely changes the way that a card looks. I would like to avoid doing something similar in UIDS.
* I would not consider the panel to be a variant of the accordion. Rather, the panel is a new design pattern and the accordion would be implementing it.
* I think a new block type is likely unavoidable in the long run unless we are going to normalize the idea of creating a collection of one item, which seems like a bad idea to me.

**Comment by bspeare** [comment]
Added the "postponed" label for now.  This is future work that we would like to have but there are other priorities currently.

**Comment by bspeare** [comment]
Closing this for now.  We can reopen if we want to revisit this approach.
