### ISSUE TITLE
Fix deployment issue

### ISSUE THREAD

**Issue by pyrello** [uiowa/uids#441]
Periodically, we are seeing this error prevent a build deployment (to the `gh-pages` branch) fail with the following error:
```
Error: The deploy step encountered an error: The process '/usr/bin/git' failed with exit code 1 ❌
```

It seems to happen intermittently.

This is a problem because it means that our docs are not always getting updated when they are supposed to and may be out of date with current changes. 

A couple potentially related issues:
* https://github.com/JamesIves/github-pages-deploy-action/issues/308
* https://github.com/actions/checkout/issues/143

**Comment by bspeare** [comment]
@pyrello is this fixed?

**Comment by pyrello** [comment]
This is not fixed, per se. My current understanding is that the issue happens when we have two processes run that complete at roughly the same time and are attempting to push to the same git branch. This results in one of them having the above error trigger. I'm not sure that we can "fix" this, but rather we can continue to improve our automation to prevent these conflicts from occurring.
