### ISSUE TITLE
Create secondary vertical navigation design variation

### ISSUE THREAD

**Issue by bspeare** [uiowa/uids#453]
Follow instructions here: https://github.com/uiowa/uids

## Create feature branch 

1. Using https://github.com/uiowa/uids/tree/main/src/components/menus/main-menu, create a feature branch with a new design variant for the sidebar navigation. 
2. Change `hidden:false` to `hidden:true` in https://github.com/uiowa/uids/blob/main/src/components/menus/main-menu/main-menu.config.yml. 
3. Create a new variant https://github.com/uiowa/uids/blob/main/src/components/menus/main-menu/main-menu.config.yml#L16-L19. 

<img width="331" alt="Screen Shot 2021-01-11 at 10 34 11 AM" src="https://user-images.githubusercontent.com/1036433/104211295-8350ba00-53f9-11eb-8196-31162e76c70f.png">

## Items to consider

- How will the navigation work with background colors?
- How many nested items?
- Does the design change if there is a left or right column?
- Responsive solution?
- Display only child pages of section or include parent page name?
- External link icon?
- Indicator for child links?
- Animation hovers?
- Horizontal variant?

## Examples

https://mentalhealth.uiowa.edu/recovery/
https://law.uiowa.edu/careers

**Comment by bewoldt** [comment]
I created a branch with my additions.
https://github.com/uiowa/uids/tree/feature_sidebar_navigation/src/components/menus/main-menu

**Comment by pyrello** [comment]
Still want to tackle this, but in 4.x?

**Comment by bspeare** [comment]
I think we did a lot of work on this in https://github.com/uiowa/uids/pull/477 that can be seen at https://uids.brand.uiowa.edu/components/detail/main-menu.html.   I'd be in favor of closing for now.
