### ISSUE TITLE
As a site owner, I can add additional style and formatting options to my tables

### ISSUE THREAD

**Issue by bspeare** [uiowa/uids#468]
As a site owner, I can add additional style options to my tables so that I can present my tabular data beyond what the basic table styles provide. 

# Proposed Solution

- [ ] Audit current table styles and compare against the list of tables below
- [ ] Provide a list of missing options to implement within the table component
- [ ] Implement the options within the component 
- [ ] **Optional:** any attributes that would need to be added to https://github.com/uiowa/uiowa/issues/2826
- [ ] https://github.com/uiowa/uids/issues/487

https://admissions.uiowa.edu/instructions/undergratuate-domestic

<img width="1232" alt="Screen Shot 2021-01-20 at 1 40 30 PM" src="https://user-images.githubusercontent.com/1036433/105226123-2f468380-5b25-11eb-9bc2-09138b71bfd0.png">

https://admissions.uiowa.edu/nursing-technical-standards

<img width="1029" alt="Screen Shot 2021-01-20 at 1 41 52 PM" src="https://user-images.githubusercontent.com/1036433/105226181-484f3480-5b25-11eb-8031-9bc94f52a411.png">

https://admissions.uiowa.edu/you-ui-schedule-test

<img width="1029" alt="Screen Shot 2021-01-20 at 1 41 52 PM" src="https://user-images.githubusercontent.com/1036433/105226235-5b620480-5b25-11eb-89b0-0e9a5cd8e9a1.png">

https://admissions.uiowa.edu/academics-undergraduate-programs-undergraduate/actsat-equivalency-table

<img width="1357" alt="Screen Shot 2021-01-20 at 1 42 27 PM" src="https://user-images.githubusercontent.com/1036433/105226293-6cab1100-5b25-11eb-935e-32dadcb049be.png">

https://admissions.uiowa.edu/academics-undergraduate-programs-undergraduate/minimum-high-school-course-requirements
https://admissions.uiowa.edu/future-students/high-school-course-requirements-international-applicants

<img width="837" alt="Screen Shot 2021-01-20 at 1 43 15 PM" src="https://user-images.githubusercontent.com/1036433/105226327-792f6980-5b25-11eb-8d8f-6a3344255ad9.png">

https://admissions.uiowa.edu/undergraduate-programs/international-undergraduate-application-deadlines

<img width="889" alt="Screen Shot 2021-01-20 at 1 43 54 PM" src="https://user-images.githubusercontent.com/1036433/105226420-949a7480-5b25-11eb-8873-6c78298e907b.png">

https://admissions.uiowa.edu/kirkwood-regional-center

<img width="954" alt="Screen Shot 2021-01-20 at 1 44 22 PM" src="https://user-images.githubusercontent.com/1036433/105226494-a8de7180-5b25-11eb-82c9-7cab8d4f5511.png">

https://admissions.uiowa.edu/academics/english-proficiency-requirements

<img width="715" alt="Screen Shot 2021-01-20 at 1 54 51 PM" src="https://user-images.githubusercontent.com/1036433/105227556-1d65e000-5b27-11eb-8c68-e6f227501e1f.png">

https://admissions.uiowa.edu/finances/estimated-costs-attendance

<img width="742" alt="Screen Shot 2021-01-20 at 1 55 26 PM" src="https://user-images.githubusercontent.com/1036433/105227653-2d7dbf80-5b27-11eb-9077-c9e3d976958a.png">

https://admissions.uiowa.edu/academics/ap (also has pdf component)

<img width="845" alt="Screen Shot 2021-01-20 at 1 55 56 PM" src="https://user-images.githubusercontent.com/1036433/105227721-42f2e980-5b27-11eb-8f1a-f63bc227188c.png">

https://admissions.uiowa.edu/academics/college-level-examination-program-clep (also has pdf component)

<img width="970" alt="Screen Shot 2021-01-20 at 1 56 25 PM" src="https://user-images.githubusercontent.com/1036433/105227761-4f774200-5b27-11eb-902f-fbbaf3a60fbb.png">

https://admissions.uiowa.edu/academics/ib

<img width="818" alt="Screen Shot 2021-01-20 at 1 56 55 PM" src="https://user-images.githubusercontent.com/1036433/105227836-63bb3f00-5b27-11eb-8734-257a4967a61e.png">

https://admissions.uiowa.edu/finances/estimated-costs-international-students
<img width="814" alt="Screen Shot 2021-01-20 at 1 57 18 PM" src="https://user-images.githubusercontent.com/1036433/105227878-72a1f180-5b27-11eb-9d9c-a68c40b46ad0.png">

https://admissions.uiowa.edu/future-students/university-iowa-student-profile **There might be a better way to display this not using tables**

<img width="807" alt="Screen Shot 2021-01-20 at 1 57 52 PM" src="https://user-images.githubusercontent.com/1036433/105227939-89484880-5b27-11eb-828e-1d33569653f6.png">

- First-Year Student Profile https://admissions.uiowa.edu/future-students/first-year-student-profile  **There might be a better way to display this not using tables**
- New Transfer Student Profile https://admissions.uiowa.edu/future-students/new-transfer-student-profile **There might be a better way to display this not using tables**
- International Student Profile https://admissions.uiowa.edu/future-students/international-student-profile **There might be a better way to display this not using tables**
- Graduate & Professional Student Profile https://admissions.uiowa.edu/future-students/graduate-professional-student-profile **There might be a better way to display this not using tables**
- High School Counselor Advisory Board https://admissions.uiowa.edu/counselors-educators/high-school-counselor-advisory-board
- Global Assessment Certificate Program (GAC) https://admissions.uiowa.edu/academics/gac **This page also has a PDF/printed component**
- You at UI Schedule 2018 https://admissions.uiowa.edu/visit-campus/youatui-schedule2018
- Cambridge International Exams (CIE) https://admissions.uiowa.edu/academics/cambridge-international-exams-cie **This page also has a PDF/printed component**
- Kirkwood Regional Center Transfer Courses at the UI https://admissions.uiowa.edu/kirkwood-regional-center
- Academic Requirements by Country https://admissions.uiowa.edu/apply/academic-requirements-country

**Comment by joewhitsitt** [comment]
Related: https://github.com/uiowa/uiowa/issues/2826

**Comment by bspeare** [comment]
Here's a screenshot of some brand table designs that we might want to use as a reference when working through this variations:  

<img width="640" alt="Screen Shot 2020-12-21 at 12 30 09 PM" src="https://user-images.githubusercontent.com/1036433/107425481-a3e95e00-6ae4-11eb-9d5b-33f79694c350.png">

**Comment by pyrello** [comment]
# Lowest hanging fruit = easiest implementation/least risk
These items build on existing options that could be better utilized to provide more options. For the most part, this would still be dependent on switching to source mode to apply classes to the `<table>` element, but would not require the editor to set classes on individual cells or rows.
* Add `.table` class by default to table?
* Add a table class to cause `<th>` cells to be highlighted wherever they are in the table (`<thead>` or `<tbody>`) that is separate from `.is-striped`.
* Add a `<small>` tag option or `.small` class style that can be applied to text.
* Add a table class that highlights a row when hovering over it.
* Add table classes that restrict the overall max-width at higher breakpoints: `.table--width-25`, `.table--width-50`, `.table--width-75`.
* Add table classes for setting a particular column to align right: `.table--column-align-right--first`, `.table--column-align-right--last`, and maybe even a set of `.table--column-align-right--1`, ...`.table--column-align-right--16` type classes?

**Comment by joewhitsitt** [comment]
Relates to https://github.com/uiowa/uiowa/issues/2748

**Comment by bspeare** [comment]
>     * Add table classes for setting a particular column to align right: `.table--column-align-right--first`, `.table--column-align-right--last`, and maybe even a set of `.table--column-align-right--1`, ...`.table--column-align-right--16` type classes?

Does the `text-align: right` option in the WYSIWYG accomplish this instead?

**Comment by bspeare** [comment]
>     * Add a `<small>` tag option or `.small` class style that can be applied to text.

The `<small>` tag option is already in place so I think we can count this one as done.

**Comment by GaryRidgway** [comment]
- [ ] Add caption styles to put a caption above the table.
- [ ] Add `.gray-borders` class that allows gray borders on all cells.
- [ ] Add  `.hover-highlight` class that allows rows to be highlighted on hover.
- [ ] Add visible outline to cells of table when initially created in the WYSIWYG.
- [ ] Add `.table--width-default` class that allows a table to shrink to only as wide as necessitated.
- [ ] Investigate options for using multiple style options in the `Styles` dropdown of the wysiwyg, or adding common configurations to it.

I agree with the implementations that @bspeare has laid out in the three comments above.

Next steps: Converse with Scott and see if these options cover the majority of his must have necessities, and if not, re-evaluate.

**Comment by GaryRidgway** [comment]
I've split the uids_base problems in to https://github.com/uiowa/uiowa/pull/3227.

After talking with Scott he seemed pretty uninterested in the style changes, and was more interested in the width changes. Sadly, this was the one item that I came to last. I hope to get to it tomorrow.
