### ISSUE TITLE
Stacked horizontal Menu needs a style update.

### ISSUE THREAD

**Issue by GaryRidgway** [uiowa/uids#478]
After completing https://github.com/uiowa/uids/issues/466 There is a clear need for the styles of the stacked version of the horizontal menu to have updated styles when below a`sm` breakpoint (768~ish pixels).

# Proposed Solution

For the `sm` breakpoint, clean up borders, use accessible colors, and update the styles of the stacked horizontal nav.

**Comment by bspeare** [comment]
This was addressed in https://github.com/uiowa/uids/pull/477.
