### ISSUE TITLE
Footer updates

### ISSUE THREAD

**Issue by pyrello** [uiowa/uids#49]
First, a point of clarification about whether a college name or department name should display first and get a bolded font treatment.

Here are a couple of screenshots and the corresponding links:

https://uiowa.github.io/uids/components/detail/footer--college.html
<img width="536" alt="Screen Shot 2020-02-20 at 10 07 08 AM" src="https://user-images.githubusercontent.com/709009/74954535-dfb58000-53c8-11ea-9350-5397091ac653.png">

https://uiowa.github.io/uids/components/detail/footer--department.html
<img width="591" alt="Screen Shot 2020-02-20 at 10 06 59 AM" src="https://user-images.githubusercontent.com/709009/74954567-ec39d880-53c8-11ea-9fef-487bd3dcba99.png">

In this case, it looks like the intention was for the college name to always be bolded and to display first if there is a department name. However, the reason it shows up this way on the demo site for the department level example is because of the way it is set in the footer.config.yml file:
https://github.com/uiowa/uids/blob/3815257cf31208410faed36dab309553db452399/components/03%20-%20global/footer/footer.config.yml#L118-L119

In Drupal, for a department site, the department name would be the site name, and the college name would be the site slogan.

Here is an example of what that looks like:
<img width="539" alt="Screen Shot 2020-02-20 at 10 12 12 AM" src="https://user-images.githubusercontent.com/709009/74954945-87cb4900-53c9-11ea-95af-9bfb8304bb36.png">

Personally, it seems right to me that the site name in every case should display first, and the college should display second, if it exists.

Second, we need to add some spacing above the socket menu because it doesn't look great when there are no social links or contact info above it. See previous screenshot.

**Comment by bspeare** [comment]
@pyrello is this still an issue or can we close this?

**Comment by pyrello** [comment]
I think this is fixed.
