### ISSUE TITLE
Create new background patterns and variants

### ISSUE THREAD

**Issue by bspeare** [uiowa/uids#492]
# Icon pattern

- [x] Create new background in UIDS for `bg--white--pattern--icon` that uses `#f3f3f3` for pattern color https://brand.uiowa.edu/sites/brand.uiowa.edu/files/2020-02/IOWA-Icon%20Pattern.zip
- [x] Add class to https://github.com/uiowa/uids/blob/main/src/components/background/_background-mixins.scss
- [x] Test on kitchen sink page
- [x] Update https://github.com/uiowa/uids/blob/main/src/components/button/button.scss with `[class*=bg-white]` in place of current `bg--white` classes

<img width="1077" alt="Screen Shot 2021-03-15 at 11 03 38 AM" src="https://user-images.githubusercontent.com/1036433/111183636-1df68200-857e-11eb-864c-d9bcd02e64ac.png">

# Brain gray pattern

- [x] Create new background in UIDS for `bg--gray--pattern--brain` that uses `#f3f3f3` for background pattern color.
- [x] Add class to https://github.com/uiowa/uids/blob/main/src/components/background/_background-mixins.scss
- [x] Test on kitchen sink page
- [x] Update https://github.com/uiowa/uids/blob/main/src/components/button/button.scss with `[class*=bg-gray]` in place of current `bg--gray` classes

<img width="1745" alt="Screen Shot 2021-03-15 at 11 07 08 AM" src="https://user-images.githubusercontent.com/1036433/111184121-a2490500-857e-11eb-8ea2-d997fa30a581.png">

# Particles

- [x] Add gold, black, gray, and white variants?
- [x] https://brand.uiowa.edu/sites/brand.uiowa.edu/files/2020-02/IOWA-Particle%20Pattern.zip

**Comment by pyrello** [comment]
Should we add the dots background as part of this? Seems more efficient to do two at the same time.

**Comment by bspeare** [comment]
Yes, I want to add https://github.com/uiowa/uids/issues/493 as well.
