### ISSUE TITLE
Allow for links in table headers and captions

### ISSUE THREAD

**Issue by GaryRidgway** [uiowa/uids#496]
Investigate and implement a way to have links properly added in the headers of the responsive header for tables, and the visible caption for responsive tables.

When a table is made responsive, it splits out and makes faux versions of the header and caption. This means that there is a possible need to find a way to either accessibly duplicate the link and have analytics still track it correclty, or pass through the click event to the correct link.

**Comment by bspeare** [comment]
I think we can close this since we switched methods for our the responsive tables.
