### ISSUE TITLE
Add utility classes to tables to change alignment

### ISSUE THREAD

**Issue by bspeare** [uiowa/uids#508]
Part of the [507 Responsive Tables](https://github.com/uiowa/uids/issues/507) epic.

Currently, the alignment of tables is set to bottom.   Do we want to add some utility classes to change these?

Related to https://github.com/uiowa/uiowa/issues/2047.

**Comment by GaryRidgway** [comment]
Do you think these would be a cell by cell option or a table by table option?

**Comment by bspeare** [comment]
I was thinking for the entire table.  What do you think?

**Comment by joewhitsitt** [comment]
I think it is stupid that the `valign` attribute is no longer html5 valid.

**Comment by GaryRidgway** [comment]
I think there are times where individual columns may want alignment, so if there is some way to do both where we can set a tablewide alignment and column alignments that would be good?

**Comment by bspeare** [comment]
@GaryRidgway that sounds good.  @joewhitsitt should we be using `valign` instead even if it is not valid?

**Comment by joewhitsitt** [comment]
It seems to be scrubbed from w3c and replaced with references to css vertical-align. no idea how long browsers will support it. probably not a long term solution

**Comment by pyrello** [comment]
As part of #518 I'm going to remove the style rule that makes table cells display as `vertical-align: bottom`. Do we still want to add additional utility classes? For all the conversation here, it doesn't seem like we've settled on anything.

**Comment by bspeare** [comment]
Is this still relevant?  Based on the conversation here it seems like we decided to not pursue alignment utility classes.  It seems like this would be work that we would want to pursue in `uiowa` with the WYISWYG https://github.com/uiowa/uiowa/issues/2195.  I think the work @pyrello did in https://github.com/uiowa/uids/issues/508#issuecomment-818076113 is sufficient.   Feel free to reopen this issue.
