### ISSUE TITLE
Style Tables with default styles.

### ISSUE THREAD

**Issue by GaryRidgway** [uiowa/uids#509]
Part of the [507 Responsive Tables](https://github.com/uiowa/uids/issues/507) epic.

Style tables with default styling closer to what we would like to see for tables. this does not include a side scrolling option. Responsive tables will not be removed during this time.

# Proposed solution

Go through tables and make the base table styles striped and with gold <th> tags.

**Comment by pyrello** [comment]
I'm going to try this one out :)
