### ISSUE TITLE
Modify the fixed header solution to be opt in

### ISSUE THREAD

**Issue by GaryRidgway** [uiowa/uids#512]
Part of the [507 Responsive Tables](https://github.com/uiowa/uids/issues/507) epic.

The current solution for sticky header responsive tables is not opt in. if we want to offer multiple options for responsive tables, we should make it opt in.

# Proposed solution
1. Strip unnecessary JS from the Sticky header JS such as accessibility enhancements.
2. Modify the javascript to only trigger the sticky header option on opted in class. I propose the class `table--sticky-headers`.

WARNING: This has only one bullet point, but because it is being performed after other things in https://github.com/uiowa/uids/issues/507 there may be some adjustments needed that are yet unforeseen.

**Comment by bspeare** [comment]
I think this can be closed via https://github.com/uiowa/uids/pull/584.
