### ISSUE TITLE
Create responsive tables formatting documentation.

### ISSUE THREAD

**Issue by GaryRidgway** [uiowa/uids#513]
Part of the [507 Responsive Tables](https://github.com/uiowa/uids/issues/507) epic.

Currently we are trying to create a responsive solution for all tables, and so in the process of working to make https://github.com/uiowa/uids/issues/507 a reality, we need to have documentation for what is acceptable formatting for responsive tables. This allows us to have definitive examples of what we will support for responsive tables and what we will not.

# Proposed solution
1. Converse about what we are willing to support.
2. Write it down and create examples for what we are willing to support.

**Comment by bspeare** [comment]
Our responsive table solution is documented with examples at https://uids.brand.uiowa.edu/latest/components/detail/tables--responsive.html so I'm going to close this for now.
