### ISSUE TITLE
Create a stacked mobile solution that users can opt in to.

### ISSUE THREAD

**Issue by GaryRidgway** [uiowa/uids#514]
Part of the [507 Responsive Tables](https://github.com/uiowa/uids/issues/507) epic.

As another responsive table option, we would like to add a stacked header table style option akin to https://codepen.io/bspeare/pen/XWpMQLP.

# Proposed solution
1. Look at http://filamentgroup.github.io/tablesaw/demo/stack.html and use their wonderful implementation as a basis for a good implementation of this.
2. Give tables the option to opt in to this using a class, I propose `table--stacked`.
3. What do we do if `table--stacked` and `table--sticky-headers` are on the same table??

**Comment by bspeare** [comment]
I think that since the work of https://github.com/uiowa/uids/pull/584, we can close this option for now.  Feel free to reopen this issue if we plan on pursuing this stacked option.
