### ISSUE TITLE
Create `card--nolink` functionality in card.js

### ISSUE THREAD

**Issue by bspeare** [uiowa/uids#531]
As a part of https://github.com/uiowa/uiowa/issues/3262, we need an opt-out class for cards that don't need the entire card clickable/linked. 

# Proposed solution

- Create `card--nolink` or similar modifier class to target in `card.js`. 
- Change https://github.com/uiowa/uids/blob/main/src/components/card/card.js#L1 to be something like `const cards = document.querySelectorAll('.card:not(.card--nolink)')` ?

**Comment by GaryRidgway** [comment]
This makes sense to me, and i think it's a pretty consistent implementation with other things that we have done before.
