### ISSUE TITLE
Hover effect for bttn--primary and bttn--secondary in Text Area

### ISSUE THREAD

**Issue by makurj** [uiowa/uids#592]
# Problem

### bttn--primary:

Inside a text area with a gold and gold types section backgrounds, `bttn--primary` has no visual hover effect and the button text color is gold. Should it be white?

![image](https://user-images.githubusercontent.com/52135878/126518674-9dcdd366-6193-4975-839d-250e67926f43.png)

### bttn--secondary:

Noticed this on https://sitenow.uiowa.edu/. The "Request Site" button (`bttn--secondary`) at the bottom of the page with a gold background gets a black button with a gold hover effect. However, that underline has no margins so it blends into the gold background. This is happening with other gold type section backgrounds.

Issue screenshot:

![image](https://user-images.githubusercontent.com/52135878/126519177-3bea06a7-943b-4eb1-8f4e-d4b76e9a7466.png)

Examples: https://sandbox.prod.drupal.uiowa.edu/text-area-buttons-hover-effect

# Steps to reproduce

# Proposed solution

**Comment by bspeare** [comment]
Related issues:
- [ ] https://github.com/uiowa/uids/issues/411
- [ ] https://github.com/uiowa/uids/issues/582 
- [ ] https://github.com/uiowa/uiowa/issues/3767

**Comment by joewhitsitt** [comment]
Is this the same as https://github.com/uiowa/uids/issues/411?

**Comment by makurj** [comment]
Part of it is. This will require UIDS changes, as I understand.

**Comment by bspeare** [comment]
Not a duplicate, which is why I list it in https://github.com/uiowa/uids/issues/592#issuecomment-884963528 as part of overall button issues that can be worked on at the same time.
