### ISSUE TITLE
Update `headline--underline` style to have an updated underline design

### ISSUE THREAD

**Issue by bspeare** [uiowa/uids#606]
# Problem

The current headline style is a little too close to a link underline. 

# Proposed solution

Update the headline underline style to look less like a link underline. 

Current:

<img width="915" alt="Screen Shot 2021-11-04 at 3 26 39 PM" src="https://user-images.githubusercontent.com/1036433/140523461-4e65949a-539c-4c06-af58-6543adb2c961.png">

Proposed:

<img width="1055" alt="Screen Shot 2021-11-04 at 3 24 20 PM" src="https://user-images.githubusercontent.com/1036433/140523454-04e9d70b-2ad9-4b5b-a7df-55f109efe524.png">

**Comment by pyrello** [comment]
Should the length of the segment of underline be proportional to the size of the header?

What if the headline happens to be shorter than the length of the underline?

**Comment by bspeare** [comment]
@pyrello great question!  Yes, perhaps a percentage based width might be more appropriate?

**Comment by joewhitsitt** [comment]
percentage off what width? aren't headings block full-width currently?

short/small headlines sound more like a content issue when picking that style

**Comment by bspeare** [comment]
I think we want to have a consistent width for all headings.   Let's start with that approach and adjust as necessary.
