### ISSUE TITLE
As a developer, I can implement a blockquote without the border and extra margin

### ISSUE THREAD

**Issue by bspeare** [uiowa/uids#624]
# Story

As a developer, I can implement a blockquote without the border and extra margin

We will need this for https://github.com/uiowa/uiowa/issues/4657. 

# Proposed solution

<img width="1368" alt="Screen Shot 2021-12-16 at 11 44 05 AM" src="https://user-images.githubusercontent.com/1036433/150153477-eb147911-7eea-493f-96d5-0254440a3fb6.png">

- Create a blockquote modifier class that removes the gold border and extra margins

**Comment by GaryRidgway** [comment]
closed by https://github.com/uiowa/uids/pull/626
