### ISSUE TITLE
Finish tabs component

### ISSUE THREAD

**Issue by pyrello** [uiowa/uids#629]
# Motivation

It appears we started working on a tabbed component at some point, but never finished it: https://uids.brand.uiowa.edu/latest/components/detail/tabs.html. The JS seems to function correctly, but the styling is not finished.

# Proposed solution

Use this screenshot as a starting point. 

<img width="2068" alt="Screen Shot 2022-02-09 at 1 43 13 PM" src="https://user-images.githubusercontent.com/1036433/153278149-f44c91b1-7fca-468a-8dcf-dda50af38e83.png">

**Comment by makurj** [comment]
When Alan picks this up :), I would like to pair on this.

**Comment by bspeare** [comment]
Do we want to be able to open tab items based on url anchor like https://github.com/uiowa/uids/issues/396?
