### ISSUE TITLE
Fix GH actions so that 3.x doesn't get deployed to `latest` in `gh-pages` branch

### ISSUE THREAD

**Issue by pyrello** [uiowa/uids#690]
When #673 was merged in, the deployment ended up in the `latest` directory in the `gh-pages` branch: https://uids.brand.uiowa.edu/latest/

Going forward we want to start using uids.brand.uiowa.edu/latest for `4.x` branch going over.

**Comment by e-marie-w** [comment]
Fixed via #848 and #850.
