### ISSUE TITLE
Remove empty region if title absent on UIowa block

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uids#7]
I removed the title and description of a UIowa block, so that just the link and link title were visible underneath the image. The region that contains the block title is still visible even if the title doesnt exist. div class="card_body" is the region, and if I display:none the region, it appears as expected. Can we have this region hidden if no interior content exists?
![Screen Shot 2020-01-10 at 1 00 55 PM](https://user-images.githubusercontent.com/3067017/72179012-c96bdb80-33a9-11ea-910b-57262fe6b7a2.png)
![Screen Shot 2020-01-10 at 1 01 04 PM](https://user-images.githubusercontent.com/3067017/72179024-cc66cc00-33a9-11ea-8a55-86056ca1d87a.png)

**Comment by pyrello** [comment]
@bspeare Do you know if this has been resolved?

**Comment by bspeare** [comment]
It's not but when I adjust the template to work for https://github.com/uiowa/uids/issues/63, I will make sure that this issue is resolved.
