### ISSUE TITLE
tables--gray-borders class doesn't have top border

### ISSUE THREAD

**Issue by bewoldt** [uiowa/uids#705]
# Problem
If you add the class `table--gray-borders` to a table to add the gray borders, there is no top border. 

<img width="875" alt="Screen Shot 2022-06-02 at 11 41 37 AM" src="https://user-images.githubusercontent.com/731952/171681340-88f809ce-e3bc-48b9-8286-2af027524473.png">

**Comment by joewhitsitt** [comment]
is this only because the table doesn't have a table header?

**Comment by bewoldt** [comment]
> is this only because the table doesn't have a table header?

Yes, the top border is missing when you do not specify a table header row. But, if you were to choose a column as your header, this would still be an issue.

**Comment by bspeare** [comment]
Closed through https://github.com/uiowa/uids/pull/735.
