### ISSUE TITLE
4.x - Button component updates

### ISSUE THREAD

**Issue by quamsta** [uiowa/uids#706]
# Motivation
The [Brand Icon Browser](https://github.com/uiowa/brand-icon-browser) needs an exportable button component that has the following features, most of which are available in [the current button component](https://uids.brand.uiowa.edu/components/detail/button--row.html):

- Background color options
- The ability to have an appropriately styled Font Awesome Icon
- A possible "block" size option that takes the full width of the container, like the following example:
<img width="287" alt="Screen Shot 2022-06-09 at 1 54 27 PM" src="https://user-images.githubusercontent.com/472923/172923010-8802c87c-6c3b-4f89-89d4-ebc3dc620a9e.png">

# Proposed solution
- [x] Incorporate a transparent background option. The transparent option needs to have an outline, otherwise the text and icon will just be floating in space.  
  - Use https://github.com/uiowa/uids/pull/711 as a starting point for base CSS. 
    -  https://github.com/uiowa/uids/blob/acc28e4f0aae5ad5b92adb3d4871d941baf808e4/src/assets/scss/_utilities.scss
    - https://github.com/uiowa/uids/blob/acc28e4f0aae5ad5b92adb3d4871d941baf808e4/src/components/button/button.scss
- [x] Add an `icon` prop that allows for the display of an arbitrary FA icon. This will likely replace the `arrow` prop.
- [x] Add a `block` prop to set display of button to be full-width.
- [x] Abstract the outline prop and related logic from the Card component into a mixin which can be shared with the button.
- [x] Change borderless class to not be element specific

```
Props:

Color:
- Primary (gold)
- Secondary (black)
- Tertiary (white)
- Transparent (with border/outline added by default)
- Link (border removed no matter what)

Borderless:
- False/True
```

**Comment by bspeare** [comment]
I think https://uids.brand.uiowa.edu/latest/?path=/story/basic-button--secondary&args=color:tertiary;outline:true;font:sans-serif is the button style closest to this.

**Comment by quamsta** [comment]
Oh snap, didn't realize that this may already available? @pyrello -- if so, I may make a branch and use it on the Icon Browser app.

**Comment by pyrello** [comment]
> Oh snap, didn't realize that this may already available? @pyrello -- if so, I may make a branch and use it on the Icon Browser app.

Sounds good. If you find anything missing from the existing button (such as block styling), you could repurpose this issue to account for changes you would like to see.

Also noting that we are added a `url` (for `href`) prop in #698 as we realized I had not added a property for the link yet.

**Comment by quamsta** [comment]
@pyrello Is a special link/url prop necessary? I was getting around that in Icon Browser by just using an href property on the component itself:

```html
          <uids-button
            href="https://github.com/uiowa/brand-icons/archive/refs/heads/main.zip"
            color="tertiary"
            class="download-button"
            :arrow="false"
            download
            >Download all
            <i class="fas fa-download"></i>
          </uids-button>
```
I guess I was assuming that `href` is a property that should always be implicitly allowed based on the fact that currently `uids-button` is always rendered as an `<a>` element. What do we gain by adding an additional `url` property? Not trying to shoot anything down, but genuinely curious.

A block style would be pretty cool, I'm manually making the above button a block element by adding `display: block` to the above element using the `.download-button` class.

**Comment by quamsta** [comment]
This is the PR that integrates the button into the Icon Browser, BTW:

https://github.com/uiowa/brand-icon-browser/pull/46

**Comment by pyrello** [comment]
Since there is already a button component, I am going to repurpose this issue to capture some information about changes that we would like to make to the button component.

**Comment by quamsta** [comment]
That's cool, feel free to rename the issue for clarity if you want

**Comment by bspeare** [comment]
Next steps for this issue that will address https://github.com/uiowa/uids/issues/710. 
```
Props:

Color:
- Primary (gold)
- Secondary (black)
- Tertiary (white)
- Transparent (with border/outline added by default)
- Link (border removed no matter what)

Borderless:
- False/True
```
