### ISSUE TITLE
4.x - Add CTA component with privacy banner/pop-up story

### ISSUE THREAD

**Issue by bspeare** [uiowa/uids#736]
# Add CTA component with privacy banner/pop-up story

- Create CTA component in 4.x
 - Create privacy acknowledgement story within CTA component
   - Create fixed bottom banner using CTA component
   - Create JS that hides the banner once the "Accept" button is clicked. 

<img width="1901" alt="Screen Shot 2022-07-27 at 4 15 27 PM" src="https://user-images.githubusercontent.com/1036433/181373759-8af8cbeb-e9e6-4b0b-ba83-7bef2e80b85b.png">

**Comment by briand44** [comment]
Blocking this until we learn more about vended solutions.
