### ISSUE TITLE
3.x / 4.x `gh-pages` deployment issues

### ISSUE THREAD

**Issue by bspeare** [uiowa/uids#751]
# Problem 

- Every time code is committed to 4.x, the latest branch is deployed to `/latest`
- Every time code is committed to the 3.x branch, the latest branch is deployed to `/latest`

When we tried to adjust 3.x from deploying to `/latest` last week, but important stylesheets were removed from the `assets/css` directory in the `gh-pages` branch: https://github.com/uiowa/uids/tree/372ea587c042beb9897566e4316ec9724cf9ee97

## Temporary fixes

- We manually added the files back to `assets/css`.
- https://uids.brand.uiowa.edu/latest/ is now displaying 3.x.   
- When the next commit into 4.x happens, `/latest` will switch back to the 4.x branch and after that when code is committed to 3.x, `/latest` will switch back to the 3.x branch without the `assets/css` files. 

# Proposed solution

Find a way to deploy 4.x to `/latest` without removing the css files in `assets/css` directory.
Examine https://github.com/uiowa/uids/actions/

**Comment by e-marie-w** [comment]
Fixed via #848 and #850.
