### ISSUE TITLE
4.x - add alerts and new alert variants

### ISSUE THREAD

**Issue by bspeare** [uiowa/uids#770]
The current alerts only have one design option: https://uids.brand.uiowa.edu/components/detail/alert.html.   In the 4.x branch, it would be ideal to have an alert/message component that has left and center variants that can be more flexible for use as:

- Alert banners for displaying a prominent message at the top of the screen.
- A section message is used to alert users to a particular section of the screen.
- Inline message to let users know when important information is available or when an action is required.

# Proposed solution
Move over the current alerts component from UIDS 3.x and create new variants/stories for the uses listed below. 
  - Hawk alert left aligned, center aligned.
  - Inline alert, outlined, left aligned, center aligned.
-  Use Font Awesome stacking styles for icon: 

```
<span class="fa-stack fa-1x"><span class="fas fa-circle fa-stack-2x"></span><span class="fa-link fas fa-stack-1x fa-inverse"></span></span>
``` 

## Hawk Alert

**Left aligned:**

<img width="1346" alt="Screen Shot 2022-09-15 at 9 56 44 AM" src="https://user-images.githubusercontent.com/1036433/190438086-f781e733-8ade-4a2e-a496-0d3d9ffdc239.png">

**Centered:** TBD

## Section message

**Left aligned:**

<img width="1385" alt="Screen Shot 2022-09-15 at 8 40 19 AM" src="https://user-images.githubusercontent.com/1036433/190438251-0ac40b99-a32a-432f-82b4-74b49e6dec39.png">
<img width="1372" alt="Screen Shot 2022-09-15 at 8 39 47 AM" src="https://user-images.githubusercontent.com/1036433/190438255-8db18e63-cf7c-463f-9960-8b88f80f4f10.png">
<img width="1376" alt="Screen Shot 2022-09-15 at 8 39 32 AM" src="https://user-images.githubusercontent.com/1036433/190438259-236da494-86ae-4dac-8d2e-69043abe63c7.png">
<img width="1346" alt="Screen Shot 2022-09-15 at 8 39 02 AM" src="https://user-images.githubusercontent.com/1036433/190438264-71ac1855-c1b3-4748-8ca1-10d14ad0b5eb.png">
<img width="1354" alt="Screen Shot 2022-09-15 at 8 38 03 AM" src="https://user-images.githubusercontent.com/1036433/190438266-6647b17a-9e3d-4e4d-9b9e-e2b41764bd06.png">

**Centered:** TBD

## Inline message

**Left aligned:**

<img width="1388" alt="Screen Shot 2022-09-14 at 3 37 50 PM" src="https://user-images.githubusercontent.com/1036433/190439807-6d826a57-e98e-43d6-9394-71ff95dbf5f3.png">
<img width="914" alt="Screen Shot 2022-09-15 at 8 48 08 AM" src="https://user-images.githubusercontent.com/1036433/190439808-1a422329-9d8c-4f0f-8570-ee2b09888f9b.png">
<img width="961" alt="Screen Shot 2022-09-15 at 8 47 24 AM" src="https://user-images.githubusercontent.com/1036433/190439810-6035894b-c86d-4b2a-ac15-8ec11e93a4dd.png">

**Centered:** TBD

**Comment by bspeare** [comment]
The proposed solution on this suggests that we replace the alerts component from 3.x with the 4.x card component w/ specific alert stories.

**Comment by cory-skeers** [comment]
Grooming convo: limiting this slice to uids specifically, and will need a follow-up issue in uiowa/uiowa for implementing in `uids_base`.

**Comment by pyrello** [comment]
I disagree with the idea of using the card component for alerts. Here is why:
- We do not want alerts to inherit most of the features of card variations.
- Alerts need minimal options - basically just type of alert. Icon should probably not be a configurable option, but instead be based on alert type.
- Card HTML markup is designed to accommodate a lot of variety that we don't need for alerts. Alerts markup can likely be much more straightforward.
- Making alerts a subset of cards means that we have to consider alerts as an added compatibility layer when adding/changing features of the card, which is already a daunting process.

**Comment by pyrello** [comment]
I want to update and elaborate on my thinking in https://github.com/uiowa/uids/issues/770#issuecomment-1677800316:

I still think that adding card-like complexity to the the alerts to achieve a more card-like experience is not desirable. On the other hand, I'm coming around to the idea of being able to have cards that have a similar color-coded option along with the ability to fill an icon could be useful.
