### ISSUE TITLE
Relative path for uiowa-primary.png is incorrect for output

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uids#839]
>I'm looking at the brand bar at, for example: https://uids.brand.uiowa.edu/components/detail/iowa-bar--narrow.html
and all of the brand bars reference an image "uiowa-primary.png" that is non-existent. - José Jimenez

https://uids.brand.uiowa.edu/assets/images/uiowa-primary.png

# Proposed Solution

- Fix relative path in iowa-bar output.

**Comment by joewhitsitt** [comment]
@pyrello can this be closed since https://github.com/uiowa/uids/pull/854 merged?

**Comment by briand44** [comment]
Is this done??

**Comment by bspeare** [comment]
I think this is not closed yet because the UIDS 3.x build process is currently not working.

**Comment by pyrello** [comment]
The build process was working, but we needed to create a 3.x release because that is all that gets built to the root domain.
