### ISSUE TITLE
Hero paragraph text is inconsistent color at different breakpoints

### ISSUE THREAD

**Issue by pyrello** [uiowa/uids#84]
https://github.com/uiowa/uids/blob/8984aa0e9910e11fc32c1ed716205c977372702c/components/02%20-%20blocks/hero-block/_hero-block.scss#L180-L186

Hero paragraph text is black by default, but at 768px and above, it is white. I guess I'm not sure if it should always be white or black, but it should probably be the same color.

**Comment by bspeare** [comment]
@pyrello thanks for finding this!
