### ISSUE TITLE
Stub out components not yet in 4.x

### ISSUE THREAD

**Issue by briand44** [uiowa/uids#895]
3.x currently has components not yet in 4.x. We should stub those out in 4.x prior to https://github.com/uiowa/uids/issues/892
```[tasklist]
### Tasks
- [x] Create a list of components that 3.x has that 4.x does not have
- [x] Use that list to create stubs in the 4.x branch.
```

**Comment by GaryRidgway** [comment]
**These are the components we have identified from v3 that should move**

Accordion
Background
Badge
Banner
Blockquote
~~Colors~~
CTA
Footer
Slider
Stat
Tables
Tabs

**Comment by pyrello** [comment]
Looks like this wasn't set to automatically close with #896
