### ISSUE TITLE
[Bug] Safari - Antonio font is not being loaded

### ISSUE THREAD

**Issue by pyrello** [uiowa/uids#897]
![screenshot_2023-11-02_at_10 29 19_am](https://github.com/uiowa/uids/assets/709009/4e88852d-bf69-4015-b6fe-8a0b9e8890fd)

Button does not appear to be using Antonio when being viewed in Safari.

**Comment by bspeare** [comment]
@pyrello I think that the fix for this is here https://github.com/uiowa/uids/blob/5c431e54074f9a5035de1ca6a28bc043a2abf8d5/src/assets/scss/fonts.scss#L4 in https://github.com/uiowa/uids/pull/759/files.
