### ISSUE TITLE
Hide components in 3.x we don't plan to migrate

### ISSUE THREAD

**Issue by briand44** [uiowa/uids#898]
Can't remove because still in use by uids_base. What does hiding entail? Removing documentation, remove/make inaccessible to fractal build process but leave css/scss.

Remove or make inaccessible to fractal build documentation files or components that we want to hide. We need to start by figuring out what the list is.

size - small to medium
```[tasklist]
### Hide in 3.x
- [x] Branding (exists in 4.x) but move Footer to standalone component until https://github.com/uiowa/uids/pull/894
- [x] Colors
- [x] Typography
- [ ] CTA - could exist in 4.x if we can get https://github.com/uiowa/uids/pull/759 approved
- [x] Button (exists in 4.x)
- [x] Alert (exists in 4.x)
- [x] Card (exists in 4.x)
- [x] Media
- [x] Menus
```

**Comment by joewhitsitt** [comment]
>CTA - could exist in 4.x if we can get https://github.com/uiowa/uids/pull/759 approved

Should this be unchecked for now, for the record?

**Comment by bspeare** [comment]
@joewhitsitt good call.

**Comment by bspeare** [comment]
Closed via https://github.com/uiowa/uids/pull/899.
