### ISSUE TITLE
Stat component transition causes abrupt change in parent component height

### ISSUE THREAD

**Issue by pyrello** [uiowa/uids#947]
# Motivation

The stat component has a feature where you can hover over it to display additional information. The hover triggers a transition on the component that causes it to move upwards by 10 pixels. While the transition itself is a smooth movement, it appears to cause the parent container to increase its height abruptly and that causes content after the stat block to jump in a disconcerting way.

![statSizeJump](https://github.com/user-attachments/assets/51e6b6d1-bf6b-4ce5-a20f-dafd537a7689)
Screen capture credit: @GaryRidgway 

# Proposed solution
Apply a transition to affect the height of the stat container so that the movement to the new height appears smooth like the movement of the stat itself.

**Comment by pyrello** [comment]
Grooming conversation... blocked until #943 is merged.

**Comment by quamsta** [comment]
Alternatively, the stat descriptions could always be there to keep that space reserved, but opacity could be changed on hover and this would eliminate height changes altogether:

https://github.com/user-attachments/assets/06761c74-9e5c-4578-a753-275967ca8f97

**Comment by bspeare** [comment]
@quamsta would that work when you have around 2400 characters in that spot?

**Comment by quamsta** [comment]
> @quamsta would that work when you have around 2400 characters in that spot?

No. 😬 I would probably rethink that amount of characters being allowed to show only on hover, since it seems like a lot.
