### ISSUE TITLE
Eliminate gap underneath images

### ISSUE THREAD

**Issue by pyrello** [uiowa/uids#99]
Images have a small gap underneath them that becomes apparent when they are wrapped in a container or are supposed to line up with a container underneath them.

Here is an example:
<img width="1666" alt="Screen Shot 2020-04-04 at 12 07 02 AM" src="https://user-images.githubusercontent.com/709009/78419139-4e147180-7608-11ea-9b0e-a5889ac92d1f.png">

It looks like this can be resolved by adding `vertical-align: top` to the `img` selector. Here is a stackoverflow answer describing this: https://stackoverflow.com/a/26608149/1375741

Here is an after shot when I applied it manually to the same section as above:
<img width="1665" alt="Screen Shot 2020-04-04 at 12 07 30 AM" src="https://user-images.githubusercontent.com/709009/78419142-5a98ca00-7608-11ea-96bd-412c5097d7d2.png">

**Comment by bspeare** [comment]
Somewhat related to #98.
